### PR TITLE
Fixes #20

### LINKED ISSUE #20: Page not found jekyll-casts

### PR DESCRIPTION
**Pull request by edheltzel**
Fixes #20 by fixing urls that link to 404 pages.
Also added new article `using-jekyll-2017`

### CODE REVIEW

**Comment by geraldb** [comment]
@ginfuru  Wow. Thanks for the fixes and updates. Keep it up.

PS: If interested you're more than welcome to join the planet jekyll org (to make contributing easier - no need for pull request, edit in browser, etc.). If interest just let me know and I send you (via GitHub) an invitation. Greeting from Vienna. Cheers. Prost.

**Comment by edheltzel** [comment]
@geraldb I'd be happy to join!

**Comment by geraldb** [comment]
@ginfuru Great. Welcome. Note: You will get an invitation (by email from GitHub) to join the Planet Jekyll org as a member. If you accept, you can update the pages in your browser  - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private; change the setting in the [github org people page](https://github.com/orgs/planetjekyll/people)).

**Comment by edheltzel** [comment]
@geraldb Thank you, sir!  Got it and thanks again.

**Pull request merged**
